### ISSUE TITLE
What is the effect of this project in practical application？

### ISSUE THREAD

**Issue by qiyeboy** [ZSShen/MeltingPot#2]
Hello, thank you for your project. I'd like to know how the project works in practice。

**Comment by ZSShen** [comment]
Hi sir,

Thanks for dropping by!

A few years ago, I built this project for self-learning purposes.  At that moment, real-world malware samples were frequently obfuscated by adversaries using various kinds of **_custom packers_**. However, with a deep dive into the collected samples, I noticed that even variants packed with different protectors still share some similar instructions, though not very often, regarding payload unpacking procedures. As a result, I tried to build this tool to cluster the collected samples, exam such similar code snippets, and generate the corresponding YARA patterns for early detection. Ideally, by providing different file parsers, MeltingPot should be able to cluster input samples with the corresponding file formats (e.g. PE, ELF, DEX). Yet, since this research topic is quite old as well as I do not have sufficient time and resources to maintain it, the plugin support is not complete. 

Best,
Andy Shen.

**Comment by qiyeboy** [comment]
@ZSShen Thank you for your reply. Do you have any documentation to explain the principle of doing this? I want to learn it. I feel that automatic signature generation is still very useful. This project is very valuable.

**Comment by ZSShen** [comment]
Hi sir,

Sorry for my late reply! 

MeltingPot aims at static signature generation, especially for the signatures targeting obfuscated malware variants. The rationale behind choosing a static approach is that I wanted to construct an efficient funnel system for app risk ranking or suspicious app detection with the scale of millions of samples, which may not be accomplished daily via dynamic analysis.

Though I did not document my design for MeltingPot, I can briefly share my original idea, which covers 3 steps, here. 
1. File Slicing
As mentioned in the previous mail, MeltingPot is supposed to have a complete plugin framework that instructs its core correlation engine on how to parse and dissect input files. For example, by specifying a Windows PE parser, the engine can parse the sections (e.g. .data .text) and overlays (resources containing images or cursors) of an input file and slice them into binary snippets. 
2. Similarity Correlation
With the binary slices produced in the first step, MeltingPot applies hierarchical clustering to group similar slices together in the second stage. In general, MultingPot adopts fuzzy hashes (or locality-sensitive hashing) for the similarity comparison of binary strings. Regarding this, the plugin framework allows developers to offer custom hash algorithms, such as SSDEP. 
3. Signature Generation 
In the final stage, MeltingPot produces a set of signatures by normalizing the representative binary strings extracted from each cluster using YARA pattern. Note that there is another plug-out module that helps the core engine to dissect the representative strings shared by all the participants of a specific cluster. Likewise, this is based on similarity comparison. 

MeltingPot is inspired by the research work (https://sites.cs.ucsb.edu/~vigna/publications/2012_DIMVA_packedmalware.pdf) led by professor Giovanni Vigna at USCB and the other paper (https://users.ece.cmu.edu/~jiyongj/papers/ccs11.pdf) guided by professor David Brumley at CMU. At that moment, many researchers tried to detect malware variants without dynamic unpacking efforts. As a result, that is why I planned and implemented MeltingPot to assist efficient static signature generation.

**Comment by qiyeboy** [comment]
@ZSShen Thank you very much for your careful guidance, it helped me a lot
